### ISSUE TITLE
Add linter to CI to ensure PEP8 improvement before merge

### ISSUE THREAD

**Issue by mathpluscode** [ucl-candi/DeepReg#10]
We can add a pre-commit check which verifies the code format before committing.

**Comment by NMontanaBrown** [comment]
* [ ] Add linter to CI to ensure code linted to Pep8 before merge during PR.

**Comment by NMontanaBrown** [comment]
See: https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#automatic-code-formatting
and 
https://github.com/psf/black#installation-and-usage
Thanks for the suggestion @tvercaut!
