### ISSUE TITLE
Test + docs: dvf

### ISSUE THREAD

**Issue by mathpluscode** [ucl-candi/DeepReg#120]
# Issue description

Support DVF models and add tests

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

**Comment by ucl-candi** [comment]
@mathpluscode can you explain how this unit tests the model/network/cond? I only see that it is called but not sure how the methods are tested for QA. Additionally, if you raise docs+tests issues, can you assign the appropriate labels so we can keep track of it?

**Comment by mathpluscode** [comment]
@NMontanaBrown l didn't know this got merged. For the testing, it just verifies that we can run it. I don't know exactly how you gonna test a NN model.

**Comment by mathpluscode** [comment]
close this as it is duplicated with #128
