### ISSUE TITLE
Test + docs: dataset/loader/nifti_loader

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#125]
# Issue description 

Expand unit tests for nifti_loader, in pytest style.

- class NiftiFileLoader
    - init, get_data, get_data_ids, get_num_images, set_group_structure, close

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests that cover class and methods, asserting that methods return values that are expected for each method.

**Comment by s-sd** [comment]
@NMontanaBrown tests for this will be pretty similar to the h5 loader so I've assigned this to myself
