### ISSUE TITLE
Test + docs: model/network/dvf.py

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#129]
# Issue description

Unit tests for ddf.py, in pytest style.

- func dvf_forward
- func build dvf_model

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for func input outputs, lint and docs.

**Comment by mathpluscode** [comment]
@acasamitjana Hi Adria, following the PR #140, the dvf model is merged with ddf model, so we now only need to add tests for `build_ddf_dvf_model`.

To test this function, we can build the function and verify the inputs and outputs for both ddf and dvf mode
