### ISSUE TITLE
Review main documentation - Create virtual environment

### ISSUE THREAD

**Issue by ebonmati** [ucl-candi/DeepReg#134]
# Issue description

Check documentation in ucl-candi.github.io (Create a virtual environment): "The recommended method is to install DeepReg in a dedicated virtual environment to avoid issues with other **dependency**." --> dependencies perhaps?

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update

**Comment by YipengHu** [comment]
@ebonmati Thanks! it would be great if you can do a thorough proof reading and group then in one PR?

**Comment by ebonmati** [comment]
> @ebonmati Thanks! it would be great if you can do a thorough proof reading and group then in one PR?

Sure, do you want me to put together all the typos/errors detected also with some suggestions?
