### ISSUE TITLE
Docs: Add recommended settings for Windows in Readme/Create a virtual Environment

### ISSUE THREAD

**Issue by ebonmati** [ucl-candi/DeepReg#138]
# Issue description

It would be useful to have also a set of recommendations for Windows in the "Create a virtual environment section". For instance, is it recommended to work with WSL+Linux or just Miniconda under Windows?

## Type of Issue

Please delete options that are not relevant.

- [X] Documentation update

**Comment by YipengHu** [comment]
@ebonmati I think the key problem is I do not have a windows machine with GPU to try. 

For CPU, I have tested a couple combinations, with tf2.x (only exception is 2.2 not available yet on win+conda - you were really unlucky there), with WSL, native, with only conda or virtualenv - they all worked.

**Comment by NMontanaBrown** [comment]
I think we can expand coverage to Windows by expanding the test matrix on Travis (let me raise a ticket and investigate). On Mac I have no problems, so will add as docs as requested. Should probably add a line or two to #1 too (about support to given OSs).
