### ISSUE TITLE
Docs: Review CoC + create contact email for any related queries

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#139]
# Issue description

CoC currently has missing blanks about how to get in touch with the team via a centralised email account. Need to update this such that there is a method to contact the team in case of issues.

## Type of Issue

Please delete options that are not relevant.
- [x] Documentation update

#### What's the expected result?
- Update the CoC such that there is an email in the [INSERT CONTACT METHOD HERE] blanks.
- We have a series of people that review the email at a semi-regular interval.

**Comment by YipengHu** [comment]
I will first have a look if we can bundle the email/contact with the new domain.
