### ISSUE TITLE
Docs: Additions to the docstrings for loaders

### ISSUE THREAD

**Issue by s-sd** [ucl-candi/DeepReg#157]
# Issue description
Make the following minor modifications/ additions to the docstrings for the loaders:
- Add a brief description of the different conditions in the grouped loader
- Either explain data organisation and directory structure for the different loaders in the docstring or point to the page where this is explained

## Type of Issue
- [x] Documentation update

**Comment by mathpluscode** [comment]
@s-sd I will add docs for grouped loader first, then for others, will wait once we merge the branches, as many branches are ongoing for loaders
