### ISSUE TITLE
Missing docstrings - network

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#16]
deepreg/model/network.py 
* [x] Missing module docstring
*  [x] Missing function docstring: build_inputs
* [x] Missing function docstring: build_model

* [x] Expand  docstring for build_backbone
* [x] Expand  docstring for build_ddf_model
> * [x] Expand dosctring for forward
> * [x] Expand docstring for add_loss_metric 

* [x] Expand  docstring for build_dvf_model
> * [x] Expand dosctring for forward
> * [x] Expand docstring for add_loss_metric 

* [x] Expand  docstring for build_cond_model
*  [x] Expand  docstring for build_seg_model

**Comment by YipengHu** [comment]
@NMontanaBrown please review 47fff87112a86cc45c666d28eff30c87d292d89d

**Comment by NMontanaBrown** [comment]
@YipengHu  Reviewed, merged!
