### ISSUE TITLE
Missing docstrings - metric

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#18]
deepreg/model/metric.py

* [ ] Missing module docstring
*  [ ] Missing class and method docstrings: MeanWrapper
*  [ ] Missing class and method docstrings: MeanDiceScore
* [ ] Missing class and method docstrings: MeanCentroidDistance
*  [ ] Missing class and method docstrings: MeanForegroundProportion

**Comment by mathpluscode** [comment]
close this issue as those classes have been removed, after using dictionary for inputs and outputs
