### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#19]

**Comment by NMontanaBrown** [comment]
@YipengHu @mathpluscode @zacbaum

**Comment by NMontanaBrown** [comment]
Ok, the basic docs needed to set up are now set up, several questions/ a more thorough review should be done addressing the following (probably not the whole gist of what needs review but what I can come up with):
* 
1. Should we merge contributing.md with readme.md?
2. Reviewing of code of conduct needs to be done by (main) maintainers/community/group/???, we should establish a channel of communication to address potential violations/issues (CoC has some gaps that need filling basically)
3. Expectations for how quickly issues/requests/comments will be addressed by maintainers should go somewhere (readme or contributions)?
4. Agree with issue #6, maybe a vision file is warranted where we outline things that are going to be addressed/worked on/maintained versus less important things? It will help prioritise what issues to work on or delegate.

**Comment by NMontanaBrown** [comment]
@YipengHu @mathpluscode

**Comment by NMontanaBrown** [comment]
Interesting links re other code of conduct for inspo: https://www.djangoproject.com/conduct/enforcement-manual/
and generally useful reading/guides from opensource.guide such as: https://opensource.guide/leadership-and-governance/

**Comment by YipengHu** [comment]
1 - i prefer the readme is a one-screen information sheet, add a link?
2 - should we establish a core dev team - those will respond to request and given a bit more credit? i'm really not experienced in this, but can try to facilitate if no one else (at least all the names in current repo should be asked)
3 - we can give an estimate only, add a link to wiki?
4 - sure
Just my initial response, open for discussion
