### ISSUE TITLE
Adding h5 data loaders 

### ISSUE THREAD

**Issue by ucl-candi** [ucl-candi/DeepReg#32]
For more information, see #5

**Comment by YipengHu** [comment]
@s-sd @mathpluscode 
We discussed a bit. I think we should simplify the folder structure for h5 files to take advantage of the format. Let's do 
- a single folder, say "train", with only two files, fixed_images.h5 and moving_images.h5;
- optionally, depends on the loader, two extra files, moving_labels.h5 and moving_images.h5
- use the keys string in the key-value pairs (value being the image/label volume) to indicate the structure instead; e.g. 
a) for paired, requires the same key-string as corresponding pair, without requiring any further naming convention;
b) for unpaired, probably no requirement;
c) for grouped, the key-string has to start with "group", separate the group index with image/label index by "-", e.g. "group1-1", "group1-2"... "group2-1", "group2-2"
d) let's not worry about multiple-parts for now (it is the same code really)

**Comment by s-sd** [comment]
@YipengHu , Thank you! I will try to make these changes today

**Comment by s-sd** [comment]
@YipengHu @mathpluscode 

I have fixed the directory structure now and have updated the h5_loader functions to incorporate these new directory structure changes. The directories now look like:

For unpaired:
- train
  - images.h5 (keys=['subject1', 'subject2' ...])
  - labels.h5 (keys=['subject1', 'subject2' ...])

For paired:
- train
  - fixed_images.h5 (keys=['subject1', 'subject2' ...])
  - fixed_labels.h5 (keys=['subject1', 'subject2' ...])
  - moving_images.h5 (keys=['subject1', 'subject2' ...])
  - moving_labels.h5 (keys=['subject1', 'subject2' ...])

For grouped:
- train
  - images.h5 (keys=['group-1-1', 'group-1-2', 'group-2-1'...])
  - labels.h5 (keys=['group-1-1', 'group-1-2', 'group-2-1'...])

The test folders for each follow a similar structure.

It would be great if you could have a look just to make sure that this sort of directory structure is similar to what you expect.

Thank you!
