### ISSUE TITLE
Restructure README to a quickstart guide with pointers to the relevant documentation

### ISSUE THREAD

**Issue by ucl-candi** [ucl-candi/DeepReg#33]
see also #6 
comment what needs to be included
mirror the two "get started"
links to tutorials
links to demos

**Comment by NMontanaBrown** [comment]
What does "comment what needs to be included, mirror the two "get started" " mean? @YipengHu

**Comment by YipengHu** [comment]
@NMontanaBrown you are doing "comment what needs to be included"

there are plans for two "get started" tutorials, registration (already in) and with demo (no demo ready yet)

**Comment by NMontanaBrown** [comment]
You mean what is missing on the README file?

**Comment by YipengHu** [comment]
are you updating this? a few docs are inter-connected with each other. we will just keep updating and close issues when at certain stage. open/new tickets again when needed.

**Comment by NMontanaBrown** [comment]
I mean, the README file should be relatively pared down with pointers to docs/tutorials where necessary. It should point users to necessary information that they need with a quickstart, see https://github.com/Project-MONAI/MONAI.We can't really do this until there is progress on tutorial docs/we create a read the docs (depends on implem of tutorials, writing of tutorial doc and writing all the code documentation). I'm going to change the name of this issue to reflect the need to cross-reference things in the README to clarify what it means.

**Comment by YipengHu** [comment]
closing this - raise specific ones if needed. @NMontanaBrown
