### ISSUE TITLE
Tutorial - Get started with demos

### ISSUE THREAD

**Issue by YipengHu** [ucl-candi/DeepReg#35]
Overview on demos 
add links to individual demos
add demo.md in /tutorials
add link to the wiki Tutorial Index

**Comment by NMontanaBrown** [comment]
Offer some demos with google colab? if no access to GPUs

**Comment by YipengHu** [comment]
was thinking about this 
- encourage all demos provided re-trained models
- let's have the scripts first - convert to notebook should be easy
