### ISSUE TITLE
Tutorial - Configuration options

### ISSUE THREAD

**Issue by YipengHu** [ucl-candi/DeepReg#36]
The detailed information on config files and their key-value pairs
add configurations.md in /tutorials
add link to the wiki Tutorial Index

**Comment by NMontanaBrown** [comment]
Related ticket #54

**Comment by NMontanaBrown** [comment]
Once this is done we can work on ticket #54 ? Facilitates dev of CLI.

**Comment by YipengHu** [comment]
> Once this is done we can work on ticket #54 ? Facilitates dev of CLI.

yup - will be get on with this tutorial

**Comment by YipengHu** [comment]
I'm closing this as a few other related newer ones raised.
