### ISSUE TITLE
Automated code formatting

### ISSUE THREAD

**Issue by tvercaut** [ucl-candi/DeepReg#44]
It's good practice to follow some code formating standards. A good means of doing so is to use an automated code formatter such as [black](https://github.com/psf/black).

See e.g. how it's done in MONAI: https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#automatic-code-formatting

**Comment by NMontanaBrown** [comment]
Related issue #10

**Comment by tvercaut** [comment]
it's indeed a duplicate
