### ISSUE TITLE
Support multiple configuration files

### ISSUE THREAD

**Issue by mathpluscode** [ucl-candi/DeepReg#47]
For now, all the configurations are put into the same file.
We should split it into data and model config, and when launching experiments, we can pass multiple configs and merge them into one

**Comment by YipengHu** [comment]
Seperate train and predict as well?

**Comment by mathpluscode** [comment]
@YipengHu prediction will use the same config as train so we are only talking about train config i think

**Comment by YipengHu** [comment]
There are clinical cases, the prediction should have a different loader.

**Comment by NMontanaBrown** [comment]
Regarding prediction using the same config as train: it is related to #56

**Comment by YipengHu** [comment]
@mathpluscode is it still relevant for the r1? close otherwise.

**Comment by mathpluscode** [comment]
close this as it's already merged.
