### ISSUE TITLE
Update README: broken link to contributing docs in README, outdated instructions for package usage, commit style guide.

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#52]
#### Issue description
1. The link to contributions doc is broken - ideally update this so it is not broken anymore.
2. The instructions for utilisation of the package using argparse could be simplified
3. Our commit messages are a bit all over the place making it hard to get the gist of updates from commits, implement a commit contrib style guide in CONTRIBUTIONS.
4. The issue template does not enforce md style of "type of issue". Fix this.
5. For setup, we have discarded requirements.txt so need to remove this from the readme to avoid confusion.

## Type of issue
Please delete options that are not relevant.

- [ ] Bug report
- [ ] New feature request
- [x] Documentation update
- [ ] Test request
- [ ] Linting request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):
N/A

#### What's the expected result?
1. Link no longer broken - direct to master file of CONTRIBUTIONS.md
2. Reduced, simpler instructions for argparse
3. Uniform guide in writing for better guidance and more uniform history in dev.
4. Appropriate md style for title in "Type of issue".
5. Remove confusing "pip install requirements.txt" when requirements are held in the setup file in the next instruction.

#### What's the actual result?
1. 404 Error when clicking on README to the CONTRIBUTIONS.md
2. N/A
3. Commit instructions a bit vague - be more explicit in wanted style to facilitate dev.
4. Literal "# # Type of Issue" returned in md formatting.
5. We have an instruction for "install requirements.txt" but no txt file in the repo, which is confusing and should be addressed.

#### Additional details / screenshot
N/A

**Comment by YipengHu** [comment]
Could make argparse just an alternative to config file?

**Comment by NMontanaBrown** [comment]
@YipengHu it does avoid the issue of having to generate config files, but I think this is a separate ticket to the one at hand. For this issue, I am working on the main docs of the three command line interfaces (train, predict, gen_tfrecord) since I just recently modified this functionality and I find the docs in README for usage quite confusing (so I cant imagine how confusing for end user!).
But expansion of argparse is potentially warranted! I'll raise a ticket and tag.
