### ISSUE TITLE
Tutorial - data sampling methods explained

### ISSUE THREAD

**Issue by YipengHu** [ucl-candi/DeepReg#65]
# Issue description
The options for sampling groups, image pairs and labels

## Type of Issue
Please delete options that are not relevant.

- [x] Documentation update

#### What's the expected result?
clearly described method that us consistent with data loaders

#### Additional details / screenshot

-
-

**Comment by YipengHu** [comment]
@s-sd Sorry Shaheer if it looked like that the changes have been made without informing/discussing with you ;) Please have a quick look at: https://github.com/ucl-candi/DeepReg/blob/56-doc-data-sampling/tutorials/sampling.md
which Yunguan will also review. All of us are still figuring out what the best way forward with the loaders. Please chip in! It is good to hold off a few things uncertain until the nifti's merge - as you are doing - to make sure h5 and nifti are consistent with each other.

**Comment by s-sd** [comment]
@YipengHu the new changes all look great! I will have a look at the sampling tutorial and will hold off on the h5 loaders until the nifti's merge
