### ISSUE TITLE
Modify output tests to pytest style and parallelise to make CI more efficient.

### ISSUE THREAD

**Issue by s-sd** [ucl-candi/DeepReg#68]
# Issue description

CI times out at 30 minutes which causes CI to fail for h5 data loaders. The total expected time it should take to finish all tests is around 40-50 minutes so an extension to the timeout is likely to fix the problem

**Comment by NMontanaBrown** [comment]
I'm not actually going to extend the CI timeout, I'm going to parallelise tests and convert to pytest style.

**Comment by s-sd** [comment]
Thank you!

**Comment by NMontanaBrown** [comment]
I need a fresh pair of eyes... For some reason, two of the tests fail out of 6 but it's not immediately obvious why. Can someone give the latest build on Travis a once over and potentially help uncover why in particular those two tests fail (where they once... didnt?)
@zacbaum @s-sd @mathpluscode

**Comment by s-sd** [comment]
@NMontanaBrown , I had a quick look and I think I spotted something. Both the tests that fail i.e. test_grouped_labeled_ddf.py and test_unpaired_unlabeled_ddf.py have the config paths specified as:
'/deepreg/config...'

instead of the usual (without the initial forward slash):
'deepreg/config...'

I think this was causing the config files not to be found. Don't know for sure that this is the problem but might be worth changing to check

**Comment by NMontanaBrown** [comment]
Fixed! Great spot @s-sd ! This means that once this is merged we can finally address your PR
