### ISSUE TITLE
Fix links and review docs after using docsify

### ISSUE THREAD

**Issue by mathpluscode** [ucl-candi/DeepReg#84]
# Issue description

## Type of Issue

- [ ] Documentation update

**Comment by YipengHu** [comment]
Please incorporate #79 - feel free to dismiss the PR if easier.

**Comment by YipengHu** [comment]
original figure are all gone...

**Comment by YipengHu** [comment]
@mathpluscode  i'm closing this now. raise a new one if necessary.
