### ISSUE TITLE
Support images of different shapes

### ISSUE THREAD

**Issue by mathpluscode** [ucl-candi/DeepReg#87]
# Issue description

For now we ask the dataset to have images of the same size, we should support resizing images of different shapes into the same shape.

There are two methods
- resize the 3D numpy array inside generator
- resize the image once it's parsed into tensor in the tf.dataset

## Type of Issue

- [ ] New feature request
- [ ] Test request

**Comment by YipengHu** [comment]
this one relates to a bigger change to account for different resolutions - see a discussion with adria here: #24

**Comment by YipengHu** [comment]
@mathpluscode are we still planning this before r1? if not please add post-r1 label

**Comment by YipengHu** [comment]
@mathpluscode  actually i'm closing this as it is duplicate #114
