### ISSUE TITLE
Demo minimum requirement

### ISSUE THREAD

**Issue by YipengHu** [ucl-candi/DeepReg#9]
# v0.1

Each demo will have an independent folder directly under the 'Demos'. For simplicity, avoiding sub-folders and additional functions/classes.

## Open accessible data
Each demo should have a 'data.py' script
Preferably, data are hosted in a reliable and efficient (not store in this repo please).

## Training
Each demo should have a 'train.py' script
This is accompanied by a config file in the same folder;

## Predicting
Each demo should have a 'predict.py' script
Ideally, 
- A pre-trained model will be available for downloading (not store in this repo please);
- Provide at least one piece of numerical metric (Dice, distance error, etc) and one piece of visualisation to show the efficacy of the registration (optimum performance is not discussed here);

## A 'readme.md' file
Briefly describe the clinical application and the need for registration
Acknowledge data source.

**Comment by ucl-candi** [comment]
@ebonmati  can you review this please.

**Comment by YipengHu** [comment]
I close this for now and moved the current content to wiki.
