### ISSUE TITLE
Test + docs: Loss/label.py

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#91]
# Issue description

Under deepreg/model/loss, need unit tests for:
- Label.py: multiple functions to do operations on labels and get metrics. Reasonably well documented and code easy to read but clearer docs useful.

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
As many unit tests that cover both the maths of the functions (expected input output) as well as docs updates and a general lint.

**Comment by NMontanaBrown** [comment]
Broken tests due to changing arg name y to tensor in foreground propotion.

**Comment by mathpluscode** [comment]
oops, sorry for the delay, for `separable_filter3d`, maybe just check the shaped, i can add them later as it's merged already.

**Comment by acasamitjana** [comment]
Hey, quick comment: loss weight is not taken into account. Should I do a PR referencing this issue in this case?

**Comment by YipengHu** [comment]
@acasamitjana can you elaborate a little what you mean by loss weight not taken into account?

**Comment by acasamitjana** [comment]
Yes sorry: I meant the weight of the label loss on the total loss (now it's weighted_loss_label = loss_label)

**Comment by YipengHu** [comment]
> Yes sorry: I meant the weight of the label loss on the total loss (now it's weighted_loss_label = loss_label)

It is a good spot @acasamitjana !
@mathpluscode did we miss anything here? The losses are not independent to each other, but is the option of label weight is provided, we should enable it.

**Comment by YipengHu** [comment]
@acasamitjana I think this needs a separate issue - do you mind raising it please.

**Comment by mathpluscode** [comment]
@acasamitjana Hi, it's a bug and I left some suggestions in the issue, generally the fix in PR is perfect, just suggesting more modifications to detect potential errors during parsing the config
