### ISSUE TITLE
Test + docs: network utils

### ISSUE THREAD

**Issue by NMontanaBrown** [ucl-candi/DeepReg#95]
# Issue description
In deepreg/model/network/util.py

Two functions 
- build_backbone: relatively easy to test, provided model backbone functions are tested for correct return types.
- build_inputs: builds input layers of some size, independent of other dependencies.

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

**Comment by mathpluscode** [comment]
@NMontanaBrown i'm wondering should we improve these tests by testing their shapes, instead of checking their types? I consider the shape checking to be essential and it might worth reopening this issue
